### ISSUE TITLE
NPM package is not available

### ISSUE THREAD

**Issue by zirkelc** [Berkmann18/cli-e2e#2]
Hi,

unfortunately, your npm package is not available anymore via: https://www.npmjs.com/package/cli-e2e

Did you remove it on purpose or has it been published under a different name?

**Comment by Berkmann18** [comment]
It hasn't been published yet as there were more to do to make it publishable and I haven't had the chance to dedicate time to that.
Any help would be appreciated.

**Comment by zirkelc** [comment]
I'm not too familiar with the process of publishing a NPM package, but I'd be willing to figure it out and help in any way. Let me know what need to be done.

**Comment by Berkmann18** [comment]
The package publication process used is one I used on other projects so that should work fine.
The only issue is to have the unit tests to see if the package works as expected. I've now set up a simple E2E one which reflects what people using this library would write to test their CLIs, I'm not fully sure how to go about testing all the process operations.

@rluvaton Have you deal with unit tests that deal with processes?

**Comment by rluvaton** [comment]
> @rluvaton Have you deal with unit tests that deal with processes?

No, but there is a good article on [Unit-testing Child Processes in node.js](https://medium.com/@stephen.k.hess/unit-testing-child-processes-in-node-js-e855f866ae27) In Medium

**Comment by Berkmann18** [comment]
> No, but there is a good article on Unit-testing Child Processes in node.js In Medium

I've taken note of this, I haven't had the time to implement what's on there as things have been really ectic.
